version: "3.9"
services:
  research_site:
    build: .
    volumes: 
      - ~/database:/database
    container_name: research_site
    env_file: 
      - .env
    ports: 
      - "8000:8000"

#  nginx:
#    build: ./nginx
#    volumes: 
#      - ~/staticroot:/staticroot
#    networks: 
#      - research_site_network
#    ports: 
#      - "80:80"
#    depends_on:
#      - research_site


# Network Config:
#networks:
#  research_site_network: 