# Generated by Django 3.1.4 on 2022-01-13 05:32

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research_core', '0015_auto_20220113_0532'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('blog_thumbnail', models.ImageField(blank=True, default=None, null=True, upload_to='blog/thumbnails')),
                ('content', tinymce.models.HTMLField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True, unique=True)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='research_core.topic')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
