#########################################################
# The nginx routing server.
#########################################################
FROM nginx
COPY ./default.conf /etc/nginx/conf.d/default.conf