# Generated by Django 3.1.4 on 2022-01-01 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research_core', '0002_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='topic',
        ),
        migrations.AddField(
            model_name='source',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='research_core.topic'),
        ),
    ]
