# Generated by Django 3.1.4 on 2022-01-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_core', '0004_auto_20220102_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='lastname',
            field=models.CharField(max_length=50),
        ),
    ]
