# Generated by Django 3.1.4 on 2022-01-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_core', '0005_auto_20220102_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='firstname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='middlename',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
