# Generated by Django 3.1.4 on 2022-01-03 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research_core', '0007_auto_20220102_0527'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Publication',
            new_name='Publisher',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='publication',
            new_name='publisher',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='publication_description',
            new_name='publisher_description',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='publication',
            new_name='publisher',
        ),
        migrations.AddField(
            model_name='source',
            name='source_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='research_core.sourcetype'),
        ),
    ]
