# Generated by Django 3.1.4 on 2022-01-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_core', '0009_auto_20220104_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='publisher_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sourcetype',
            name='source_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
