# Generated by Django 3.1.4 on 2022-01-13 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_core', '0014_auto_20220105_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['-date_published'], 'verbose_name_plural': 'Blog Posts'},
        ),
    ]
